services:
  nginx:
    image: nginx:1.21-alpine
    container_name: nginx_server_rasp
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./php
    container_name: php_fpm_rasp
    volumes:
      - ./www:/var/www/html
